version: '3'
services:
  miniconda:
    container_name: miniconda-jupyter
    build: .
    volumes:
      - ./jupyter-notebook/notebooks:/opt/notebooks
      - ./machine-learning:/home/machine-learning
    ports:
      - "8888:8888"
